### PR TITLE
Add accidentals and transpose

### PR DESCRIPTION
**Pull request by jaredonline**
Adds a new transpose type (discovered this when debugging guitar standard notation) and adds the accidental `sattr` to `note`.

Added a test for the accidental and will get in the habit of adding tests for new features [=

### CODE REVIEW

**Comment by kddnewton** [comment]
LGTM - are you using the Lilypond part of this gem? I was thinking about splitting it out into a separate plugin so that it would be clear how to make other serializers for this thing. Not entirely sure.

**Comment by jaredonline** [comment]
I wasn't planning on it. I'm using Lilypond's test suite to test my own XML importer for an app I'm working on. Lilypond -> Business Logic Storage -> Vexflow for rendering.

**Comment by kddnewton** [comment]
Cool, so if I strip this down to just the XML parsing, it should still work for you? I assume we're the only users ATM.

**Comment by jaredonline** [comment]
Yep! I was also wondering how'd you feel about hosting this on Rubygems at some point in the future? Once its stabalized a bit? I have a feeling I'll be messing with the nodes / attributes a bit while I work through this Lilypond suite.

**Comment by kddnewton** [comment]
Yeah that's totally fine. I'm actually surprised I never published it in the first place. I'll push it up there once I strip out the cruft, probably this week/weekend.

**Pull request merged**
